amount = int(input("enter the total amount of money you want to convert"))
y = int((amount % 5)/2)
print(y) 
x = int((amount - y)/5)
print(y) 
print(x) 
z = int(y % 2)
print(y) 
print(x) 
print(z) 
print("the minimum number of coins for the conversion is:")
print(f"5 - {x}  2 - {y}  1 - {z}")
