import turtle

def draw_letter(letter, size):

  if letter.lower() == 'h':
    turtle.left(90)
    turtle.forward(size)
    turtle.right(90)
    turtle.forward(size / 2)
    turtle.right(90)
    turtle.forward(size)
    turtle.left(180)
    turtle.forward(size / 2)
    turtle.left(90)
  elif letter.lower() == 'a':
    turtle.left(90)
    turtle.forward(size)
    turtle.right(180)
    turtle.forward(size / 2)
    turtle.left(90)
    turtle.forward(size / 2)
    turtle.left(90)
    turtle.forward(size / 2)
    turtle.right(180)
    turtle.forward(size)
  elif letter.lower() == 'p':
    turtle.left(90)
    turtle.forward(size)
    turtle.right(90)
    turtle.forward(size / 2)
    turtle.right(90)
    turtle.forward(size / 2)
    turtle.right(90)
    turtle.forward(size / 2)
    turtle.left(180)
    turtle.forward(size / 2)
  elif letter.lower() == 'y':
    turtle.left(90)
    turtle.forward(size / 2)
    turtle.right(90)
    turtle.forward(size / 4)
    turtle.right(90)
    turtle.forward(size / 2)
    turtle.left(90)
    turtle.forward(size / 4)
    turtle.left(90)
    turtle.forward(size / 2)
  elif letter.lower() == 'n':
    turtle.left(90)
    turtle.forward(size)
    turtle.right(135)
    turtle.forward(size * 2**0.5 / 2)
    turtle.left(135)
    turtle.forward(size)
  elif letter.lower() == 'e':
    turtle.left(90)
    turtle.forward(size)
    turtle.right(90)
    turtle.forward(size / 2)
    turtle.left(90)
    turtle.forward(size / 2)
    turtle.left(90)
    turtle.forward(size / 2)
    turtle.left(90)
    turtle.forward(size / 2)
    turtle.right(90)
    turtle.forward(size / 2)
  elif letter.lower() == 'w':
    turtle.left(90)
    turtle.forward(size)
    turtle.right(135)
    turtle.forward(size * 2**0.5 / 2)
    turtle.left(45)
    turtle.forward(size * 2**0.5 / 2)
    turtle.right(135)
    turtle.forward(size)
  elif letter.lower() == 'r':
    turtle.left(90)
    turtle.forward(size)
    turtle.right(90)
    turtle.forward(size / 2)
    turtle.right(90)
    turtle.forward(size / 2)
    turtle.right(90)
    turtle.forward(size / 2)
    turtle.left(180)
    turtle.forward(size / 2)
    turtle.left(90)
    turtle.forward(size / 2)
turtle.penup()
turtle.goto(-75,0)
turtle.pendown()
draw_letter('h',50)
# draw_letter('a',50)
# draw_letter('p',50)
# draw_letter('p',50)
# draw_letter('y',50)
# turtle.penup()
# turtle.goto(25,0)
# turtle.pendown()
# draw_letter('n',50)
# draw_letter('e',50)
# draw_letter('w',50)
# turtle.penup()
# turtle.goto(125,0)
# turtle.pendown()
# draw_letter('y',50)
# draw_letter('e',50)
# draw_letter('a',50)
# draw_letter('r',50)
