file = open("id.txt", "w")
file.write("Janek \n")
file.write("Slizewicz \n")
file.write("Cracow Economical Uniwersity \n")
file.write("Applied informatics \n")
file.close()
file = open("id.txt", "r")
file_content = file.read()
print(file_content)
file.close()